import 'package:fpdart/fpdart.dart';

import '../../../../core/error/failure.dart';
import '../entities/budget.dart';
import '../entities/budget_category_allocation.dart';
import '../entities/budget_summary.dart';
import '../entities/budget_trend_point.dart';

/// Domain/Data boundary for [Budget] and [BudgetCategoryAllocation], and
/// everything derived from them (contracts/budgets_repository.md).
/// Local-only, so this interface *is* the feature's contract. No method
/// throws to the caller (constitution Principle VII).
///
/// Its implementation composes 007's `FinanceRepository` and
/// `CategoryRepository` interfaces (research.md Decision 1): every "actual
/// spend" figure comes from 007's own `getCategoryBreakdown`, never from a
/// second query over `finance_entries` (FR-016), and nothing here ever
/// writes to a 007 table (FR-022).
abstract class BudgetsRepository {
  /// Creates a new budget for [month] (`'YYYY-MM'`, FR-001).
  /// [idempotencyKey] is generated by the caller at "Save" time; a retried
  /// call with the same key returns the already-persisted budget rather
  /// than creating a second one (FR-017). Returns
  /// `BudgetAlreadyExistsForMonthFailure` if an active budget already
  /// exists for [month] — the caller should route the user to editing it.
  /// `ValidationFailure` for a malformed [month] or a negative
  /// [expectedIncomeMinorUnits].
  Future<Either<Failure, Budget>> createBudget({
    required String idempotencyKey,
    required String month,
    int? expectedIncomeMinorUnits,
  });

  /// Sets a budget's expected income figure (FR-003) — `null` clears it.
  /// Category allocations are managed via the dedicated methods below.
  Future<Either<Failure, Budget>> editBudget({
    required String budgetId,
    int? expectedIncomeMinorUnits,
  });

  /// Soft-deletes a budget after the caller has shown a confirmation
  /// (FR-011). Never touches `FinanceEntry`/`Category` data (FR-022). Its
  /// month becomes free for a new budget.
  Future<Either<Failure, Unit>> deleteBudget(String budgetId);

  /// Creates a new budget for [targetMonth] by copying every allocation of
  /// [sourceBudgetId] (FR-012), in one DB transaction. The two budgets
  /// share no ongoing link afterward — editing one never affects the
  /// other. The source's expected income is copied too, as a starting
  /// point. Fails with `BudgetAlreadyExistsForMonthFailure` if
  /// [targetMonth] already has an active budget; a retry with the same
  /// [idempotencyKey] returns the budget the first call created.
  Future<Either<Failure, Budget>> copyBudgetToMonth({
    required String idempotencyKey,
    required String sourceBudgetId,
    required String targetMonth,
  });

  /// Adds a planned allocation for [categoryId] to [budgetId] (FR-001).
  /// [categoryId] MUST reference an active, expense-type 007 `Category`
  /// (`ValidationFailure` otherwise; `NotFoundFailure` if unknown). Rejects
  /// a negative [plannedAmountMinorUnits] (FR-002 — zero is accepted) and a
  /// second allocation for the same category
  /// (`DuplicateBudgetAllocationFailure`); a retry with the same
  /// [idempotencyKey] returns the row the first call wrote (FR-017).
  Future<Either<Failure, BudgetCategoryAllocation>>
  addBudgetCategoryAllocation({
    required String idempotencyKey,
    required String budgetId,
    required String categoryId,
    required int plannedAmountMinorUnits,
  });

  /// Edits an existing allocation's planned amount (FR-010).
  Future<Either<Failure, BudgetCategoryAllocation>>
  editBudgetCategoryAllocation({
    required String allocationId,
    required int plannedAmountMinorUnits,
  });

  /// Removes a category from a budget (FR-010). Its spending (if any)
  /// becomes "unbudgeted" for that month afterward (FR-007). Hard delete —
  /// no audit trail needed for plan data (research.md Decision 5).
  Future<Either<Failure, Unit>> removeBudgetCategoryAllocation(
    String allocationId,
  );

  /// Full computed detail for [month]: the budget itself, its
  /// [BudgetSummary] (planned/actual/remaining/percentage/over-budget,
  /// FR-005/FR-006/FR-009), per-category lines (FR-005/FR-008) and
  /// unbudgeted spending (FR-007). Recomputed from 007's live data on every
  /// call — there is no cache to go stale after an expense is added,
  /// edited or deleted elsewhere in the app.
  ///
  /// Returns `BudgetMonthDetail.empty` (not a Failure) when [month] has no
  /// budget, so the caller can render the FR-018 empty state.
  ///
  /// 018 FR-009: spend that needs a missing exchange rate is never a
  /// failure — it blocks only the lines, items and totals that depend on it
  /// (see `BudgetSummary`); planned amounts always come back.
  Future<Either<Failure, BudgetMonthDetail>> getBudgetForMonth(String month);

  /// 021: the live [getBudgetForMonth] (FR-031) — emits now, then again
  /// whenever the budget, its allocations, the month's expense entries,
  /// categories, exchange rates or the primary currency change (locally or
  /// through sync). Equal re-reads are not re-emitted.
  Stream<Either<Failure, BudgetMonthDetail>> watchBudgetForMonth(String month);

  /// 022 D1: every active budget of every month, oldest month first, for the
  /// data export. Soft-deleted budgets are left out. A plain read.
  Future<Either<Failure, List<Budget>>> getAllBudgets();

  /// 022 D1: every allocation of every active budget, for the data export.
  /// Allocations of a soft-deleted budget are left out. A plain read.
  Future<Either<Failure, List<BudgetCategoryAllocation>>> getAllAllocations();

  /// The most recent month strictly before [month] that has an active
  /// budget, or `null` when there is none — the copy-forward source the
  /// FR-018 empty state offers (FR-012: "typically the most recent").
  Future<Either<Failure, Budget?>> getMostRecentBudgetBefore(String month);

  /// Planned-vs-actual points for the [monthsBack] months ending at
  /// [endMonth] (default: the current month), oldest first (FR-014) —
  /// overall when [categoryId] is `null`, otherwise for that one category.
  /// Months with no budget are included as zero-planned points with
  /// `hasBudget: false`; the caller applies the "at least 2 budgeted
  /// months" check via `BudgetTrendHistory.hasEnoughHistory`.
  ///
  /// 018 FR-009: a figure that needs a missing exchange rate comes back as
  /// `null` on its own point (see `BudgetTrendPoint`) — the trend as a
  /// whole never fails for it.
  Future<Either<Failure, List<BudgetTrendPoint>>> getBudgetTrend({
    String? categoryId,
    int monthsBack = 6,
    String? endMonth,
  });

  /// 021: the live [getBudgetTrend] (FR-031), re-read on the same changes
  /// as [watchBudgetForMonth].
  Stream<Either<Failure, List<BudgetTrendPoint>>> watchBudgetTrend({
    String? categoryId,
    int monthsBack = 6,
    String? endMonth,
  });
}
