import 'package:fpdart/fpdart.dart';

import '../../../../core/error/failure.dart';
import '../../../../core/money/money.dart';
import '../entities/category_breakdown_item.dart';
import '../entities/finance_entry.dart';
import '../entities/finance_entry_type.dart';
import '../entities/finance_history_filter.dart';
import '../entities/finance_summary.dart';

/// Domain/Data boundary for [FinanceEntry] and everything derived from it
/// (constitution Principle VI). Local-only — this feature has no network
/// layer, so this interface *is* its contract. No method throws to the
/// caller (Principle VII).
abstract class FinanceRepository {
  /// Records a new income or expense entry (FR-001/FR-002).
  /// [idempotencyKey] is generated by the caller at "Save" time; a retried
  /// call with the same key returns the already-persisted entry rather than
  /// creating a second one (FR-021). Rejects a non-positive [amount]
  /// (FR-003) and a [categoryId] whose category type does not match [type].
  /// [amount]'s currency is persisted with the entry and never changes on
  /// its own (018 FR-002).
  Future<Either<Failure, FinanceEntry>> addEntry({
    required String idempotencyKey,
    required String categoryId,
    required FinanceEntryType type,
    required Money amount,
    required DateTime date,
    String? note,
  });

  /// Edits amount/category/date/note of an existing entry (FR-019). `type`
  /// is re-derived from the (possibly new) category rather than accepted
  /// directly, so an edit can never leave type and category mismatched.
  /// Sets `editedAt`. [amount]'s currency replaces the entry's currency —
  /// changing it is an explicit user edit (018 FR-002).
  Future<Either<Failure, FinanceEntry>> editEntry({
    required String entryId,
    required String categoryId,
    required Money amount,
    required DateTime date,
    String? note,
  });

  /// Soft-deletes an entry immediately (FR-020, research.md Decision 8).
  /// The caller shows the confirmation and the undo affordance; the commit
  /// itself is not deferred, so a process death mid-undo-window leaves the
  /// delete applied rather than a half-state.
  Future<Either<Failure, Unit>> deleteEntry(String entryId);

  /// Un-sets `deletedAt` for an entry deleted within the undo window. A
  /// no-op success (not an error) if the entry is not currently
  /// soft-deleted — defensive against a stale or duplicate undo tap.
  Future<Either<Failure, FinanceEntry>> restoreEntry(String entryId);

  /// One entry by id, soft-deleted or not — what the edit form resolves the
  /// entry it was opened on. Soft-deleted rows are included so a restore
  /// flow can read back what it is restoring.
  Future<Either<Failure, FinanceEntry>> getEntryById(String entryId);

  /// Filtered, paginated history (FR-012/FR-013), newest date first,
  /// soft-deleted rows excluded.
  Future<Either<Failure, List<FinanceEntry>>> getHistory({
    FinanceHistoryFilter? filter,
    int limit = 50,
    int offset = 0,
  });

  /// Per-currency income and expense totals for [period] (FR-014), computed
  /// by SQL aggregate, never by summing a fetched list client-side. Amounts
  /// in different currencies are never added together here (018 FR-008) —
  /// `GetFinanceSummary` converts them into the primary currency.
  Future<Either<Failure, FinancePeriodTotals>> getSummaryTotals(
    DateRange period,
  );

  /// Per-category, per-currency totals for [period], ordered by the
  /// category's largest single-currency total (FR-015). [type] narrows the
  /// breakdown to one direction when given. Unconverted — see
  /// `GetCategoryBreakdown`.
  Future<Either<Failure, List<CategoryCurrencyTotals>>> getCategoryTotals(
    DateRange period, {
    FinanceEntryType? type,
  });

  /// 021: [getHistory]'s first [limit] rows, re-read whenever entries
  /// change — locally or through sync (FR-031). Only the loaded window is
  /// watched; paging raises [limit].
  Stream<Either<Failure, List<FinanceEntry>>> watchHistory({
    FinanceHistoryFilter? filter,
    required int limit,
  });

  /// 021: [getSummaryTotals], re-read whenever entries change (FR-031).
  Stream<Either<Failure, FinancePeriodTotals>> watchSummaryTotals(
    DateRange period,
  );

  /// FR-017: whether any entry exists at all, including soft-deleted ones —
  /// what separates the true first-use empty state from "your filter
  /// matched nothing" (FR-018).
  Future<Either<Failure, bool>> hasAnyEntry();
}
