import 'package:fpdart/fpdart.dart';

import '../../../../core/error/failure.dart';
import '../entities/category_breakdown_item.dart';
import '../entities/finance_entry.dart';
import '../entities/finance_entry_type.dart';
import '../entities/finance_history_filter.dart';
import '../entities/finance_summary.dart';

/// Domain/Data boundary for [FinanceEntry] and everything derived from it
/// (constitution Principle VI). Local-only — this feature has no network
/// layer, so this interface *is* its contract. No method throws to the
/// caller (Principle VII).
abstract class FinanceRepository {
  /// Records a new income or expense entry (FR-001/FR-002).
  /// [idempotencyKey] is generated by the caller at "Save" time; a retried
  /// call with the same key returns the already-persisted entry rather than
  /// creating a second one (FR-021). Rejects [amountMinorUnits] <= 0
  /// (FR-003) and a [categoryId] whose category type does not match [type].
  Future<Either<Failure, FinanceEntry>> addEntry({
    required String idempotencyKey,
    required String categoryId,
    required FinanceEntryType type,
    required int amountMinorUnits,
    required DateTime date,
    String? note,
  });

  /// Edits amount/category/date/note of an existing entry (FR-019). `type`
  /// is re-derived from the (possibly new) category rather than accepted
  /// directly, so an edit can never leave type and category mismatched.
  /// Sets `editedAt`.
  Future<Either<Failure, FinanceEntry>> editEntry({
    required String entryId,
    required String categoryId,
    required int amountMinorUnits,
    required DateTime date,
    String? note,
  });

  /// Soft-deletes an entry immediately (FR-020, research.md Decision 8).
  /// The caller shows the confirmation and the undo affordance; the commit
  /// itself is not deferred, so a process death mid-undo-window leaves the
  /// delete applied rather than a half-state.
  Future<Either<Failure, Unit>> deleteEntry(String entryId);

  /// Un-sets `deletedAt` for an entry deleted within the undo window. A
  /// no-op success (not an error) if the entry is not currently
  /// soft-deleted — defensive against a stale or duplicate undo tap.
  Future<Either<Failure, FinanceEntry>> restoreEntry(String entryId);

  /// Filtered, paginated history (FR-012/FR-013), newest date first,
  /// soft-deleted rows excluded.
  Future<Either<Failure, List<FinanceEntry>>> getHistory({
    FinanceHistoryFilter? filter,
    int limit = 50,
    int offset = 0,
  });

  /// Total income, total expenses, and net for [period] (FR-014), computed
  /// by SQL aggregate, never by summing a fetched list client-side.
  Future<Either<Failure, FinanceSummary>> getSummary(DateRange period);

  /// Per-category totals for [period], descending by amount (FR-015).
  /// [type] narrows the breakdown to one direction when given.
  Future<Either<Failure, List<CategoryBreakdownItem>>> getCategoryBreakdown(
    DateRange period, {
    FinanceEntryType? type,
  });

  /// FR-017: whether any entry exists at all, including soft-deleted ones —
  /// what separates the true first-use empty state from "your filter
  /// matched nothing" (FR-018).
  Future<Either<Failure, bool>> hasAnyEntry();
}
