import 'package:equatable/equatable.dart';

import '../../../transactions/domain/entities/money_transaction.dart';

/// Where a scan is in its life: `processing → needsReview → (confirmed |
/// discarded)`, with `failed` reachable from `processing` whenever the
/// pipeline could not produce anything reviewable (009 data-model.md).
enum ScanStatus { processing, needsReview, confirmed, discarded, failed }

/// One user-initiated session of "photograph a paper, turn it into entries".
///
/// Holds the image and the batch-level choices that apply to everything
/// parsed out of it — the default direction and the optional occasion tag —
/// but never any money of its own. The money only ever exists as
/// `MoneyTransaction` rows created at confirm time (009 research.md
/// Decision 5).
class OcrScan extends Equatable {
  const OcrScan({
    required this.id,
    required this.idempotencyKey,
    required this.sourceImagePath,
    required this.rotationDegrees,
    required this.status,
    required this.createdAt,
    this.cropBounds,
    this.occasionId,
    this.defaultDirection,
    this.completedAt,
    this.deletedAt,
  });

  final String id;

  /// Regenerated by the review screen for each confirm attempt and carried
  /// into `confirmScanBatch`, where the unique index on it is what makes a
  /// double-tapped confirm a no-op instead of a second batch (FR-021).
  final String idempotencyKey;

  /// The prepared (cropped/rotated/enhanced) image, inside the app's own
  /// sandboxed storage. Never a remote URL — the bytes are never uploaded
  /// (FR-019, FR-023).
  final String sourceImagePath;

  /// Serialized crop rectangle applied during preparation, kept so a past
  /// scan can be explained later. Audit metadata, not an instruction to
  /// re-process.
  final String? cropBounds;
  final int rotationDegrees;
  final ScanStatus status;

  /// Set when the user tags the whole batch to an occasion at review time
  /// (FR-014); every entry confirmed afterwards is saved as that occasion's
  /// contribution rather than a plain transaction.
  final String? occasionId;

  /// The batch-level fallback direction (FR-005). `null` means the user has
  /// not chosen one, in which case any entry without its own direction is
  /// not yet confirm-eligible.
  final TransactionDirection? defaultDirection;
  final DateTime createdAt;

  /// Set when the scan reaches `confirmed` or `discarded`.
  final DateTime? completedAt;

  /// Soft-delete tombstone (FR-023). Deleting a scan also removes its
  /// source image file, but never the transactions it already produced.
  final DateTime? deletedAt;

  bool get isDeleted => deletedAt != null;
  bool get isTerminal =>
      status == ScanStatus.confirmed || status == ScanStatus.discarded;

  /// Whether this scan's confirmed entries are recorded against an occasion
  /// (008) rather than as plain transactions.
  bool get isOccasionTagged => occasionId != null;

  OcrScan copyWith({
    String? idempotencyKey,
    String? sourceImagePath,
    String? cropBounds,
    int? rotationDegrees,
    ScanStatus? status,
    String? occasionId,
    bool clearOccasionId = false,
    TransactionDirection? defaultDirection,
    DateTime? completedAt,
    DateTime? deletedAt,
  }) {
    return OcrScan(
      id: id,
      idempotencyKey: idempotencyKey ?? this.idempotencyKey,
      sourceImagePath: sourceImagePath ?? this.sourceImagePath,
      cropBounds: cropBounds ?? this.cropBounds,
      rotationDegrees: rotationDegrees ?? this.rotationDegrees,
      status: status ?? this.status,
      occasionId: clearOccasionId ? null : (occasionId ?? this.occasionId),
      defaultDirection: defaultDirection ?? this.defaultDirection,
      createdAt: createdAt,
      completedAt: completedAt ?? this.completedAt,
      deletedAt: deletedAt ?? this.deletedAt,
    );
  }

  @override
  List<Object?> get props => [
    id,
    idempotencyKey,
    sourceImagePath,
    cropBounds,
    rotationDegrees,
    status,
    occasionId,
    defaultDirection,
    createdAt,
    completedAt,
    deletedAt,
  ];
}
