import 'package:fpdart/fpdart.dart';

import '../../../../core/error/failure.dart';
import '../../../../core/money/money.dart';
import '../../../transactions/domain/entities/money_transaction.dart';
import '../entities/occasion.dart';
import '../entities/occasion_attachment.dart';
import '../entities/occasion_detail.dart';
import '../entities/occasion_filter.dart';

/// Domain/Data boundary for occasions and the participant contributions
/// recorded under them (constitution Principle VI).
///
/// The three `*ParticipantContribution` methods deliberately do **not** write
/// to `money_transactions` themselves — they delegate to
/// `TransactionsRepository`, which is what guarantees a contribution is the
/// exact same row whether it is read from the occasion screen or from the
/// person's own profile (FR-005, FR-010).
abstract class OccasionsRepository {
  /// Creates a new occasion (FR-001). [idempotencyKey] is generated by the
  /// caller at "Save" time; a retried call with the same key returns the
  /// already-persisted occasion rather than creating a second one (FR-019).
  /// Rejects an empty-after-trim [name] or [type].
  Future<Either<Failure, Occasion>> createOccasion({
    required String idempotencyKey,
    required String name,
    required DateTime date,
    required String type,
    String? notes,
  });

  /// Edits name/date/type/notes of an existing occasion (FR-012).
  ///
  /// Deliberately does NOT retroactively change `countsTowardBalance` on
  /// contributions already recorded, even when [type] changes to or from
  /// `condolence`: an unrelated edit must never silently move someone's
  /// balance (research.md Decision 3).
  Future<Either<Failure, Occasion>> editOccasion({
    required String occasionId,
    required String name,
    required DateTime date,
    required String type,
    String? notes,
  });

  /// Hides an occasion from the default list while leaving it, its
  /// attachments, and its contributions fully intact — the contributions
  /// keep counting toward balances (FR-014).
  Future<Either<Failure, Unit>> archiveOccasion(String occasionId);

  /// Restores a previously archived occasion (FR-014).
  Future<Either<Failure, Unit>> restoreOccasion(String occasionId);

  /// Soft-deletes an occasion AND cascades to soft-delete every linked
  /// contribution in one DB transaction, appending a `deleted`
  /// `TransactionAuditEntry` per contribution (FR-013, research.md
  /// Decision 5). Wrapping both steps in one transaction is what makes a
  /// half-applied cascade — contributions gone, occasion left behind —
  /// impossible.
  ///
  /// The caller must already have shown the "N contributions will be
  /// removed" confirmation; [getOccasionDetail] supplies N.
  Future<Either<Failure, Unit>> deleteOccasion(String occasionId);

  /// Records one participant's contribution (FR-003/FR-004/FR-005).
  ///
  /// [countsTowardBalance] defaults to `false` only when the parent
  /// occasion's type is `condolence` and the caller passes `null`
  /// (FR-018); every other type defaults to `true`. Rejects a non-positive
  /// [amount], an unknown/deleted occasion, and a blank [personId].
  Future<Either<Failure, MoneyTransaction>> addParticipantContribution({
    required String idempotencyKey,
    required String occasionId,
    required String personId,
    required Money amount,
    required TransactionDirection direction,
    required DateTime date,
    bool? countsTowardBalance,
    String? note,
  });

  /// Edits a contribution's amount/direction/date/note (FR-010). Identical
  /// semantics whether called from the occasion detail screen or the
  /// person's own profile: both act on the same underlying
  /// `MoneyTransaction` row.
  Future<Either<Failure, MoneyTransaction>> editParticipantContribution({
    required String transactionId,
    required Money amount,
    required TransactionDirection direction,
    required DateTime date,
    String? note,
  });

  /// Removes one contribution after the caller has shown a confirmation
  /// (FR-011). Soft-deletes the underlying `MoneyTransaction`, so it leaves
  /// both the occasion's participant list and the person's own history.
  Future<Either<Failure, Unit>> removeParticipantContribution(
    String transactionId,
  );

  /// Full detail for one occasion: the occasion itself, its computed
  /// `OccasionSummary` (FR-007/FR-008), its participant rows (FR-016) each
  /// carrying that person's independently computed overall balance status
  /// (FR-009), and its active attachments.
  Future<Either<Failure, OccasionDetail>> getOccasionDetail(String occasionId);

  /// The occasions list, reverse-chronological by date (FR-015), optionally
  /// narrowed by [filter]. Archived occasions are excluded unless
  /// [includeArchived] is `true`; soft-deleted ones are never returned.
  Future<Either<Failure, List<Occasion>>> getOccasionsList({
    OccasionFilter? filter,
    bool includeArchived = false,
  });

  /// Records a photo the presentation layer already captured via
  /// `AttachmentPickerService` and which that service already copied into
  /// the app's private storage (FR-017). This method persists the reference
  /// only — it never opens a picker itself.
  Future<Either<Failure, OccasionAttachment>> addOccasionAttachment({
    required String occasionId,
    required String filePath,
  });

  /// Soft-deletes an attachment after the caller has shown a confirmation
  /// (FR-017).
  Future<Either<Failure, Unit>> removeOccasionAttachment(String attachmentId);
}
