import 'package:fpdart/fpdart.dart';

import '../../../../core/error/failure.dart';
import '../../../../core/money/money.dart';
import '../entities/money_transaction.dart';
import '../entities/overview_summary.dart';
import '../entities/person_balance.dart';

/// Domain/Data boundary for everything about a [MoneyTransaction] and the
/// balances/overview derived from it (constitution Principle VI).
abstract class TransactionsRepository {
  /// Records a regular given/received transaction (FR-004), stored in
  /// [amount]'s own currency (018 FR-001/FR-002). [idempotencyKey]
  /// is generated by the caller at "Save" time; a retried call with the same
  /// key returns the already-persisted transaction rather than creating a
  /// second one (FR-020, SC-006). Rejects `personId` equal to the app's own
  /// user (Edge Cases: no self-transactions) and `amount <= 0` (FR-005).
  Future<Either<Failure, MoneyTransaction>> addTransaction({
    required String idempotencyKey,
    required String personId,
    required Money amount,
    required TransactionDirection direction,
    required DateTime date,
    String? note,
  });

  /// Records a repayment against an existing balance (FR-011). Accepts an
  /// amount larger than the current outstanding balance and lets the
  /// resulting balance flip direction rather than rejecting it (FR-012).
  /// Same idempotency contract as [addTransaction]. `direction` is always
  /// inferred from the current balance, never accepted from the caller.
  Future<Either<Failure, MoneyTransaction>> recordRepayment({
    required String idempotencyKey,
    required String personId,
    required Money amount,
    required DateTime date,
    String? note,
  });

  /// Edits amount/direction/date/note of an existing transaction (FR-015).
  /// `kind` is never accepted here — it is immutable after creation
  /// (Clarifications). Sets `editedAt` and appends a `TransactionAuditEntry`
  /// with the pre-edit values in the same DB transaction.
  Future<Either<Failure, MoneyTransaction>> editTransaction({
    required String transactionId,
    required Money amount,
    required TransactionDirection direction,
    required DateTime date,
    String? note,
  });

  /// Soft-deletes a transaction after the caller has already shown the
  /// "cannot be undone" confirmation (FR-016) and appends a `deleted`
  /// `TransactionAuditEntry` in the same DB transaction.
  Future<Either<Failure, Unit>> deleteTransaction(String transactionId);

  /// Full chronological history for one person, active (non-deleted) rows
  /// only, each entry carrying its edited/kind/direction metadata (FR-010).
  Future<Either<Failure, List<MoneyTransaction>>> getPersonHistory(
    String personId,
  );

  /// Computed net balance + status for one person (FR-008, FR-009), in the
  /// primary currency. 018: when a currency involved has no exchange rate
  /// the balance comes back as `PersonBalance.blocked` naming the missing
  /// currencies (FR-009) — never a 1:1 conversion.
  Future<Either<Failure, PersonBalance>> getPersonBalance(String personId);

  /// [getPersonBalance] for many people in one read — one conversion
  /// context and one grouped query instead of per-person queries — for
  /// lists that show every row's balance at once. Each balance is computed
  /// exactly as [getPersonBalance] computes it; every id in [personIds] is
  /// present in the result (a person with no transactions is settled).
  Future<Either<Failure, Map<String, PersonBalance>>> getPersonBalances(
    List<String> personIds,
  );

  /// Consolidated totals/groupings across all people, active and archived
  /// (FR-013, FR-014; Clarifications: archived people with a non-zero
  /// balance are included). 018: totals are in the primary currency and are
  /// `null` (blocked) when a contributing currency has no exchange rate.
  Future<Either<Failure, OverviewSummary>> getOverview();

  /// 021: [getPersonHistory], re-read whenever transactions change —
  /// locally or through sync (FR-031). Emits only when the result changes.
  Stream<Either<Failure, List<MoneyTransaction>>> watchPersonHistory(
    String personId,
  );

  /// 021: [getPersonBalance], re-read whenever transactions, people,
  /// exchange rates or the primary currency change (FR-031).
  Stream<Either<Failure, PersonBalance>> watchPersonBalance(String personId);

  /// 021: [getPersonBalances], re-read on the same tables as
  /// [watchPersonBalance] (FR-031).
  Stream<Either<Failure, Map<String, PersonBalance>>> watchPersonBalances(
    List<String> personIds,
  );

  /// 021: [getOverview], re-read on the same tables as
  /// [watchPersonBalance] (FR-031).
  Stream<Either<Failure, OverviewSummary>> watchOverview();

  /// FR-010a: whether at least one MoneyTransaction record exists at all —
  /// including soft-deleted rows (`deletedAt IS NOT NULL`). A since-deleted
  /// transaction still proves the app was previously used.
  Future<Either<Failure, bool>> hasAnyTransaction();
}
