import 'package:fpdart/fpdart.dart';

import '../../../../core/error/failure.dart';
import '../../../../core/money/money.dart';
import '../entities/money_transaction.dart';
import '../entities/overview_summary.dart';
import '../entities/person_balance.dart';

/// Domain/Data boundary for everything about a [MoneyTransaction] and the
/// balances/overview derived from it (constitution Principle VI).
abstract class TransactionsRepository {
  /// Records a regular given/received transaction (FR-004). [idempotencyKey]
  /// is generated by the caller at "Save" time; a retried call with the same
  /// key returns the already-persisted transaction rather than creating a
  /// second one (FR-020, SC-006). Rejects `personId` equal to the app's own
  /// user (Edge Cases: no self-transactions) and `amount <= 0` (FR-005).
  Future<Either<Failure, MoneyTransaction>> addTransaction({
    required String idempotencyKey,
    required String personId,
    required Money amount,
    required TransactionDirection direction,
    required DateTime date,
    String? note,
  });

  /// Records a repayment against an existing balance (FR-011). Accepts an
  /// amount larger than the current outstanding balance and lets the
  /// resulting balance flip direction rather than rejecting it (FR-012).
  /// Same idempotency contract as [addTransaction]. `direction` is always
  /// inferred from the current balance, never accepted from the caller.
  Future<Either<Failure, MoneyTransaction>> recordRepayment({
    required String idempotencyKey,
    required String personId,
    required Money amount,
    required DateTime date,
    String? note,
  });

  /// Edits amount/direction/date/note of an existing transaction (FR-015).
  /// `kind` is never accepted here — it is immutable after creation
  /// (Clarifications). Sets `editedAt` and appends a `TransactionAuditEntry`
  /// with the pre-edit values in the same DB transaction.
  Future<Either<Failure, MoneyTransaction>> editTransaction({
    required String transactionId,
    required Money amount,
    required TransactionDirection direction,
    required DateTime date,
    String? note,
  });

  /// Soft-deletes a transaction after the caller has already shown the
  /// "cannot be undone" confirmation (FR-016) and appends a `deleted`
  /// `TransactionAuditEntry` in the same DB transaction.
  Future<Either<Failure, Unit>> deleteTransaction(String transactionId);

  /// Full chronological history for one person, active (non-deleted) rows
  /// only, each entry carrying its edited/kind/direction metadata (FR-010).
  Future<Either<Failure, List<MoneyTransaction>>> getPersonHistory(
    String personId,
  );

  /// Computed net balance + status for one person (FR-008, FR-009).
  Future<Either<Failure, PersonBalance>> getPersonBalance(String personId);

  /// Consolidated totals/groupings across all people, active and archived
  /// (FR-013, FR-014; Clarifications: archived people with a non-zero
  /// balance are included).
  Future<Either<Failure, OverviewSummary>> getOverview();

  /// Creates a `MoneyTransaction` with `kind = occasionContribution` linked
  /// to [occasionId] (008). Called only by `OccasionsRepositoryImpl` —
  /// Presentation goes through `OccasionsRepository.addParticipantContribution`
  /// instead, so the occasion-specific validation (the occasion must exist
  /// and not be deleted) lives in exactly one place. Same idempotency
  /// contract as [addTransaction].
  Future<Either<Failure, MoneyTransaction>> addOccasionContribution({
    required String idempotencyKey,
    required String personId,
    required String occasionId,
    required Money amount,
    required TransactionDirection direction,
    required bool countsTowardBalance,
    required DateTime date,
    String? note,
  });

  /// Every non-deleted contribution row for one occasion, across all
  /// participants, oldest first — backs the occasion detail screen's
  /// participant list and its `OccasionSummary` aggregation (008).
  Future<Either<Failure, List<MoneyTransaction>>> getContributionsForOccasion(
    String occasionId,
  );

  /// Occasion id → occasion name, for every occasion-linked row in
  /// [personId]'s history (008). Read in one query so the person's history
  /// list can label each contribution with its occasion without a lookup
  /// per row — and read here, from the shared `AppDatabase`, rather than by
  /// depending on the `occasions` feature, which depends on this one
  /// (constitution Principle II: the arrow points one way).
  Future<Either<Failure, Map<String, String>>> getOccasionNamesForPerson(
    String personId,
  );

  /// FR-010a: whether at least one MoneyTransaction record exists at all —
  /// including soft-deleted rows (`deletedAt IS NOT NULL`). A since-deleted
  /// transaction still proves the app was previously used.
  Future<Either<Failure, bool>> hasAnyTransaction();
}
